### ISSUE TITLE
Raspberry Pi 

### ISSUE THREAD

**Issue by domwoe** [ecto/duino#32]
Hi,

has anyone tried to use duino with an Raspberry Pi (with Raspbian)?

The communication using duino is working perfectly on my Mac but if I use my app on the pi   the serial communication does not work properly as you can see as follows:

1359682670868 duino info binding serial events
1359682670888 duino receiveA#C�   >�2   $$$�  
1359682671387 duino info board ready

What could be wrong? I tried baud rates of 9600 and 115200.

**Comment by misiek08** [comment]
I'm running rPi + Arudingo Mega 2560 over USB. When I enable my simple script:

```
var arduino = require('duino'),
    board = new arduino.Board({device: "ACM0", debug: true}), sensor;
board.on("ready", function(){
    console.log("gotowa, zaczynam pinmołdy");
    board.pinMode(42, 'out');
    board.digitalWrite(42, board.HIGH);
    board.pinMode(8, 'out');
    board.analogWrite(8, 90);

});
board.on("data", function(data){
    console.log(data);
});
```

I got info about connecting, board found and writing data to board. Nothing happens (no command is executed), when I press Ctrl+C script show me all it got from Arduino board (all the debug info) and hangs. I'm installing duino using

```
npm install -g duino
```

and script above.

Let me know if you need console output.

**Comment by ajw685** [comment]
Check out heimcontrol.js

The code should help you figure out a solution

**Comment by misiek08** [comment]
I don't need such big project as heim. I just reported that buffer which handles data from Arduino is send to script only on shutdown, not "live" when Arduino send real data.
